# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
NODE_COUNT = 2



Vagrant.configure("2") do |config|
  config.vm.define "manager" do |manager|
    manager.vm.box = "centos/7"
    manager.vm.hostname = "manager"
    manager.vm.box_url = "centos/7"
    # manager.vm.boot_timeout = 800
    # manager.ssh.insert_key = true
    # manager.ssh.private_key_path = [".ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    manager.vm.network :private_network, ip: "192.168.56.5"
    manager.vm.network "public_network", bridge: "wlp2s0"
    manager.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    manager.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2024]
      v.customize ["modifyvm", :id, "--name", "manager"]
    end
  config.vm.provision "shell", path: "bootstrap.sh", privileged: true
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "worker#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "worker#{i}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{i + 10}"
      subconfig.vm.network "public_network", bridge: "wlp2s0"
      subconfig.vm.network :forwarded_port, guest: 22, host: "1012#{i + 2}", id: "ssh"
	  # subconfig.ssh.private_key_path = [".ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
	  # subconfig.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      subconfig.vm.provider :virtualbox do |v|
      	v.customize ["modifyvm", :id, "--memory", 2024]
      	v.name = "worker#{i}"
      end
    config.vm.provision "shell", path: "bootstrap.sh", privileged: true
    end
   end
end
